//! Codegen for the enchantment tables (Part 10.2's "generate, don't type").
//!
//! The data is parsed at BUILD time and emitted as static Rust tables, so `serde_json`
//! stays a build-dependency and never enters the crate's runtime dependency graph — the
//! core stays lean and natively testable, per Part 10.0.
//!
//! Multi-version (Part 13.3): the directory is GLOBBED, not a single named file. Each
//! `data/enchantments-*.json` becomes one `VersionTable` in the generated `TABLES` array,
//! ordered newest-first. Adding a version is a pure-data operation — drop in a file with the
//! same shape and its `_provenance` block, and it appears in the registry with no code change.

use std::{collections::BTreeMap, env, fs, path::Path};

fn main() {
    println!("cargo:rerun-if-changed=data");
    println!("cargo:rerun-if-changed=build.rs");

    // Collect every dataset, parsed, keyed by a sortable version tuple so the registry is
    // ordered newest-first regardless of filesystem order.
    let mut datasets: Vec<(Vec<i64>, String, serde_json::Value)> = Vec::new();
    for entry in fs::read_dir("data").expect("data directory missing") {
        let path = entry.unwrap().path();
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
        if !name.starts_with("enchantments-") || !name.ends_with(".json") {
            continue;
        }
        let raw = fs::read_to_string(&path).unwrap_or_else(|_| panic!("cannot read {name}"));
        let v: serde_json::Value =
            serde_json::from_str(&raw).unwrap_or_else(|_| panic!("{name} is not valid JSON"));
        let version = v["_provenance"]["minecraft_version"]
            .as_str()
            .unwrap_or_else(|| panic!("{name} has no _provenance.minecraft_version"))
            .to_string();
        datasets.push((version_key(&version), version, v));
    }
    assert!(
        !datasets.is_empty(),
        "no data/enchantments-*.json files found"
    );
    // Newest first, so TABLES[0] is the default and the registry reads top-down like a
    // version picker. Descending on the numeric tuple.
    datasets.sort_by(|a, b| b.0.cmp(&a.0));
    // A duplicated version string would silently shadow — two files claiming 1.21.3 is a
    // transcription mistake, not a valid registry, so reject it at build time.
    for w in datasets.windows(2) {
        assert_ne!(
            w[0].1, w[1].1,
            "two datasets both declare version {}",
            w[0].1
        );
    }

    let mut out = String::new();
    out.push_str("// GENERATED by build.rs from data/enchantments-*.json — do not edit.\n\n");
    out.push_str(STRUCT_DEF);

    // The newest version's string, kept as MC_VERSION for backwards compatibility with any
    // consumer that still wants a single default. New code should use TABLES / default_table.
    let newest = &datasets[0].1;
    out.push_str(&format!(
        "/// The newest offered version — the default. Prefer `default_table()`; this stays for\n/// consumers that only ever want one version's label.\npub const MC_VERSION: &str = {newest:?};\n\n"
    ));

    // One statics block per version, with a sanitised identifier suffix.
    let mut table_entries: Vec<String> = Vec::new();
    for (_, version, v) in &datasets {
        let suffix = ident_suffix(version);
        emit_version(&mut out, &suffix, version, v);
        table_entries.push(format!(
            "    VersionTable {{ mc_version: {version:?}, enchantments: &ENCH_{suffix}, item_enchantability: &ITEM_ENCH_{suffix} }},",
        ));
    }

    out.push_str(&format!(
        "/// Every offered enchantment dataset, newest first. `TABLES[0]` is the default.\npub static TABLES: [VersionTable; {}] = [\n{}\n];\n",
        table_entries.len(),
        table_entries.join("\n"),
    ));

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("tables.rs");
    fs::write(dest, out).unwrap();
}

/// The `EnchantmentData` layout, emitted once and shared by every version's table.
const STRUCT_DEF: &str = "pub struct EnchantmentData {\n    pub name: &'static str,\n    pub weight: i32,\n    pub max_level: i32,\n    pub min_cost: (i32, i32),\n    pub max_cost: (i32, i32),\n    /// Per-level ITEM cost multiplier for anvil combining. Book multiplier is half\n    /// (see anvil::book_cost_multiplier). Verified against the wiki: fire_aspect=4\n    /// matches its documented 4x-from-item / 2x-from-book.\n    pub anvil_cost: i32,\n    /// Indices into THIS version's ENCHANTMENTS. Already the SYMMETRIC closure — see the\n    /// data file. Version-scoped: never mix with another version's table.\n    pub exclusive_with: &'static [usize],\n    /// Items this can be ROLLED onto at an enchanting table (primary set).\n    pub primary_items: &'static [&'static str],\n    /// Items this can be APPLIED to, including via anvil/book — broader than\n    /// primary_items (e.g. sharpness is primary on swords but supported on axes too).\n    pub supported_items: &'static [&'static str],\n    /// Whether an enchanting table can produce this at all (7 of 1.21.3's 42 cannot be).\n    pub in_enchanting_table: bool,\n    pub treasure: bool,\n}\n\n";

/// A sortable numeric tuple for a version string like `1.21.3` -> `[1, 21, 3]`. Non-numeric
/// components sort as 0; shorter versions pad implicitly via tuple comparison.
fn version_key(version: &str) -> Vec<i64> {
    version
        .split('.')
        .map(|p| p.parse::<i64>().unwrap_or(0))
        .collect()
}

/// A Rust-identifier-safe suffix for a version: `1.21.3` -> `1_21_3`.
fn ident_suffix(version: &str) -> String {
    version
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

/// Emit `ENCH_<suffix>` and `ITEM_ENCH_<suffix>` statics for one dataset.
fn emit_version(out: &mut String, suffix: &str, version: &str, v: &serde_json::Value) {
    let ench = v["enchantments"].as_object().unwrap();
    let names: Vec<&String> = ench.keys().collect();
    let idx: BTreeMap<&str, usize> = names
        .iter()
        .enumerate()
        .map(|(i, n)| (n.as_str(), i))
        .collect();

    let tags = v["item_tags"].as_object().unwrap();
    let resolve = |key: &serde_json::Value| -> Vec<String> {
        match key.as_str() {
            None => vec![],
            Some(s) => {
                let t = s.trim_start_matches('#').replace("minecraft:", "");
                let t = t.strip_prefix("enchantable/").unwrap_or(&t);
                tags.get(t)
                    .and_then(|x| x.as_array())
                    .map(|a| a.iter().map(|i| i.as_str().unwrap().to_string()).collect())
                    .unwrap_or_default()
            }
        }
    };

    out.push_str(&format!(
        "// --- {version} ---\nstatic ENCH_{suffix}: [EnchantmentData; {}] = [\n",
        names.len()
    ));
    for name in &names {
        let e = &ench[name.as_str()];
        let excl: Vec<String> = e["exclusive_with"]
            .as_array()
            .unwrap()
            .iter()
            .map(|x| idx[x.as_str().unwrap()].to_string())
            .collect();
        // The enchanting table rolls from primary_items; fall back to supported_items
        // when an enchantment declares no primary set.
        let mut items = resolve(&e["primary_items"]);
        if items.is_empty() {
            items = resolve(&e["supported_items"]);
        }
        let items: Vec<String> = items.iter().map(|i| format!("{i:?}")).collect();
        // Anvil applicability uses the full supported set (fall back to primary if a
        // future enchantment declares no supported_items).
        let mut supported = resolve(&e["supported_items"]);
        if supported.is_empty() {
            supported = resolve(&e["primary_items"]);
        }
        let supported: Vec<String> = supported.iter().map(|i| format!("{i:?}")).collect();
        out.push_str(&format!(
            "    EnchantmentData {{ name: {:?}, weight: {}, max_level: {}, min_cost: ({}, {}), max_cost: ({}, {}), anvil_cost: {}, exclusive_with: &[{}], primary_items: &[{}], supported_items: &[{}], in_enchanting_table: {}, treasure: {} }},\n",
            name,
            e["weight"].as_i64().unwrap(),
            e["max_level"].as_i64().unwrap(),
            e["min_cost"]["base"].as_i64().unwrap(),
            e["min_cost"]["per_level"].as_i64().unwrap(),
            e["max_cost"]["base"].as_i64().unwrap(),
            e["max_cost"]["per_level"].as_i64().unwrap(),
            e["anvil_cost"].as_i64().unwrap(),
            excl.join(", "),
            items.join(", "),
            supported.join(", "),
            e["in_enchanting_table"].as_bool().unwrap(),
            e["treasure"].as_bool().unwrap(),
        ));
    }
    out.push_str("];\n");

    let ie = v["item_enchantability"].as_object().unwrap();
    out.push_str(&format!(
        "static ITEM_ENCH_{suffix}: [(&str, i32); {}] = [\n",
        ie.len()
    ));
    for (item, val) in ie {
        out.push_str(&format!("    ({item:?}, {}),\n", val.as_i64().unwrap()));
    }
    out.push_str("];\n\n");
}
