//! Codegen for the enchantment tables (Part 10.2's "generate, don't type").
//!
//! The data is parsed at BUILD time and emitted as static Rust tables, so `serde_json`
//! stays a build-dependency and never enters the crate's runtime dependency graph — the
//! core stays lean and natively testable, per Part 10.0.

use std::{collections::BTreeMap, env, fs, path::Path};

fn main() {
    println!("cargo:rerun-if-changed=data/enchantments-1.21.3.json");
    println!("cargo:rerun-if-changed=build.rs");

    let raw = fs::read_to_string("data/enchantments-1.21.3.json").expect("data file missing");
    let v: serde_json::Value = serde_json::from_str(&raw).expect("data file is not valid JSON");

    let version = v["_provenance"]["minecraft_version"].as_str().unwrap();
    let mut out = String::new();
    out.push_str("// GENERATED by build.rs from data/enchantments-1.21.3.json — do not edit.\n\n");
    out.push_str(&format!(
        "/// Minecraft version this table encodes. Surface it in any UI (Part 10.2).\npub const MC_VERSION: &str = {version:?};\n\n"
    ));

    // Enchantments, sorted so the generated order is deterministic and diffable.
    let ench = v["enchantments"].as_object().unwrap();
    let names: Vec<&String> = ench.keys().collect();
    let idx: BTreeMap<&str, usize> = names
        .iter()
        .enumerate()
        .map(|(i, n)| (n.as_str(), i))
        .collect();

    out.push_str("pub struct EnchantmentData {\n    pub name: &'static str,\n    pub weight: i32,\n    pub max_level: i32,\n    pub min_cost: (i32, i32),\n    pub max_cost: (i32, i32),\n    pub anvil_cost: i32,\n    /// Indices into ENCHANTMENTS. Already the SYMMETRIC closure — see the data file.\n    pub exclusive_with: &'static [usize],\n    /// Items this can be rolled onto at an enchanting table.\n    pub primary_items: &'static [&'static str],\n    /// Whether an enchanting table can produce this at all. 7 of the 42 cannot be:\n    /// filtering only on item applicability would wrongly roll mending, soul_speed, etc.\n    pub in_enchanting_table: bool,\n    pub treasure: bool,\n}\n\n");

    let tags = v["item_tags"].as_object().unwrap();
    let resolve = |key: &serde_json::Value| -> Vec<String> {
        match key.as_str() {
            None => vec![],
            Some(s) => {
                let t = s.trim_start_matches('#').replace("minecraft:", "");
                let t = t.strip_prefix("enchantable/").unwrap_or(&t);
                tags.get(t)
                    .and_then(|x| x.as_array())
                    .map(|a| a.iter().map(|i| i.as_str().unwrap().to_string()).collect())
                    .unwrap_or_default()
            }
        }
    };

    out.push_str(&format!(
        "pub static ENCHANTMENTS: [EnchantmentData; {}] = [\n",
        names.len()
    ));
    for name in &names {
        let e = &ench[name.as_str()];
        let excl: Vec<String> = e["exclusive_with"]
            .as_array()
            .unwrap()
            .iter()
            .map(|x| idx[x.as_str().unwrap()].to_string())
            .collect();
        // The enchanting table rolls from primary_items; fall back to supported_items
        // when an enchantment declares no primary set.
        let mut items = resolve(&e["primary_items"]);
        if items.is_empty() {
            items = resolve(&e["supported_items"]);
        }
        let items: Vec<String> = items.iter().map(|i| format!("{i:?}")).collect();
        out.push_str(&format!(
            "    EnchantmentData {{ name: {:?}, weight: {}, max_level: {}, min_cost: ({}, {}), max_cost: ({}, {}), anvil_cost: {}, exclusive_with: &[{}], primary_items: &[{}], in_enchanting_table: {}, treasure: {} }},\n",
            name,
            e["weight"].as_i64().unwrap(),
            e["max_level"].as_i64().unwrap(),
            e["min_cost"]["base"].as_i64().unwrap(),
            e["min_cost"]["per_level"].as_i64().unwrap(),
            e["max_cost"]["base"].as_i64().unwrap(),
            e["max_cost"]["per_level"].as_i64().unwrap(),
            e["anvil_cost"].as_i64().unwrap(),
            excl.join(", "),
            items.join(", "),
            e["in_enchanting_table"].as_bool().unwrap(),
            e["treasure"].as_bool().unwrap(),
        ));
    }
    out.push_str("];\n\n");

    // item -> enchantability
    let ie = v["item_enchantability"].as_object().unwrap();
    out.push_str(&format!(
        "/// Sorted by item name; look up with a binary search.\npub static ITEM_ENCHANTABILITY: [(&str, i32); {}] = [\n",
        ie.len()
    ));
    for (item, val) in ie {
        out.push_str(&format!("    ({item:?}, {}),\n", val.as_i64().unwrap()));
    }
    out.push_str("];\n");

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("tables.rs");
    fs::write(dest, out).unwrap();
}
