#!/usr/bin/env bash
# utilities.mc — capture golden vectors for java.util.Random from a real JDK (Part 10.1).
#
# The point of this script is that the ground truth is generated, never hand-typed: a
# transcription slip here would be indistinguishable from a bug in our JavaRandom, which
# defeats the entire purpose of having a reference.
#
# Emits a Rust table on stdout. Regenerate with:
#   scripts/gen-java-vectors.sh > crates/enchant/tests/vectors/java_random.rs
set -euo pipefail

command -v java >/dev/null 2>&1 || {
    echo "error: no JDK found. On Arch: sudo pacman -S jdk-openjdk" >&2
    exit 1
}

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# Bounds deliberately mix powers of two (which hit Java's special-cased branch) with
# non-powers (which hit the rejection loop). Testing only one kind passes while leaving
# half of next_int_bound unverified.
cat > "$WORK/Gen.java" <<'JAVA'
import java.util.Random;

public class Gen {
    public static void main(String[] args) {
        long[] seeds  = {0L, 1L, -1L, 12345L, 42L, 1000000L, -8379241L, 9223372036854775807L};

        // Small bounds are what enchanting actually uses. The large ones exist solely to
        // exercise nextInt's rejection loop: rejection probability is (2^31 % bound)/2^31,
        // which is ~1e-8 for bound=100 but ~50% for 2^30+3. Without a bound in that range
        // the vectors pass even if the rejection loop is deleted entirely — verified by
        // mutation testing, and it is exactly the "right 99% of the time" bug the guide warns of.
        int[]  bounds = {2, 3, 4, 5, 7, 8, 16, 21, 50, 100, 1000,
                         1073741827, 1431655765, 2000000000, 2147483647};

        System.out.println("// GENERATED by scripts/gen-java-vectors.sh — do not edit by hand.");
        System.out.println("// Ground truth: " + System.getProperty("java.vm.name")
                           + " " + System.getProperty("java.version"));
        System.out.println();

        System.out.println("/// (seed, bound, [10 successive nextInt(bound) draws])");
        System.out.println("pub const NEXT_INT_BOUND: &[(i64, i32, [i32; 10])] = &[");
        for (long s : seeds) {
            for (int b : bounds) {
                Random r = new Random(s);
                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < 10; i++) {
                    if (i > 0) sb.append(", ");
                    sb.append(r.nextInt(b));
                }
                System.out.printf("    (%di64, %d, [%s]),%n", s, b, sb);
            }
        }
        System.out.println("];");
        System.out.println();

        System.out.println("/// (seed, [10 successive nextInt() draws])");
        System.out.println("pub const NEXT_INT: &[(i64, [i32; 10])] = &[");
        for (long s : seeds) {
            Random r = new Random(s);
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < 10; i++) {
                if (i > 0) sb.append(", ");
                sb.append(r.nextInt());
            }
            System.out.printf("    (%di64, [%s]),%n", s, sb);
        }
        System.out.println("];");
        System.out.println();

        // Printed as raw bits: a decimal float literal would round-trip through two
        // different parsers and could hide a low-bit discrepancy, which is precisely
        // what this vector exists to catch.
        System.out.println("/// (seed, [10 successive nextFloat() draws, as raw IEEE-754 bits])");
        System.out.println("pub const NEXT_FLOAT_BITS: &[(i64, [u32; 10])] = &[");
        for (long s : seeds) {
            Random r = new Random(s);
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < 10; i++) {
                if (i > 0) sb.append(", ");
                sb.append("0x").append(Integer.toHexString(Float.floatToRawIntBits(r.nextFloat())));
            }
            System.out.printf("    (%di64, [%s]),%n", s, sb);
        }
        System.out.println("];");
        System.out.println();

        System.out.println("/// (seed, [6 successive nextLong() draws])");
        System.out.println("pub const NEXT_LONG: &[(i64, [i64; 6])] = &[");
        for (long s : seeds) {
            Random r = new Random(s);
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < 6; i++) {
                if (i > 0) sb.append(", ");
                sb.append(r.nextLong());
            }
            System.out.printf("    (%di64, [%s]),%n", s, sb);
        }
        System.out.println("];");
        System.out.println();

        // Mixed-call sequence: each vector above re-seeds and uses one method, so none of
        // them would catch a method that advances the stream by the wrong number of steps.
        System.out.println("/// Interleaved calls from seed 12345, in order. Catches wrong stream advancement.");
        System.out.println("/// Ops: 0=nextInt(100) 1=nextInt(16) 2=nextFloat bits 3=nextInt()");
        System.out.println("pub const MIXED: &[(u8, i64)] = &[");
        Random r = new Random(12345L);
        int[] ops = {0,1,2,3,1,1,0,2,3,0,1,2,2,3,0,1,0,3,2,1};
        for (int op : ops) {
            long v = switch (op) {
                case 0 -> r.nextInt(100);
                case 1 -> r.nextInt(16);
                case 2 -> Float.floatToRawIntBits(r.nextFloat()) & 0xFFFFFFFFL;
                default -> r.nextInt();
            };
            System.out.printf("    (%d, %di64),%n", op, v);
        }
        System.out.println("];");
    }
}
JAVA

if command -v jshell >/dev/null 2>&1 && ! command -v javac >/dev/null 2>&1; then
    # JRE-only installs still ship jshell on some distros; single-file source mode below
    # covers the common case, so this is just a clearer error than a javac-not-found.
    echo "error: need a full JDK (javac), not just jshell" >&2
    exit 1
fi

java "$WORK/Gen.java"
